### ISSUE TITLE
Support value property in declarative mode

### ISSUE THREAD

**Issue by alelb** [fabbricadigitale/paper-chip#44]
### Use case 1
`<paper-chip>xyz-label</paper-chip>`
value (property) : undefined
label (visual) : xyz-label

### Use case 2
`<paper-chip value="xyz"></paper-chip>` 
value (property) : xyz
label (visual) : xyz

### Use case 3
`<paper-chip value="xyz">xyz-label</paper-chip>`
value (property) : xyz
label (visual) : xyz-label

**Comment by leodido** [comment]
:+1:

**Comment by leodido** [comment]
I implemented the declarative part (with a slot fallback) of the use case 1.

The property `label` on the chip instance does not exist yet.

**Comment by leodido** [comment]
Currently this is the behavior.

When the `<paper-chip>` contains an HTML element with slot attribute equal to "label" (ie., `<div slot="label">content</div>`), its content becomes the visible content of the `<paper-chip>`.

Otherwise the `<paper-chip>` element fallbacks to use the text content in its light DOM, if any, as the visible content.

This behavior is similar to the `<option>` label attribute behavior ([ref.](https://developer.mozilla.org/it/docs/Web/HTML/Element/option)).

**Comment by leodido** [comment]
Also use case 3 works now. :tada:

**Comment by alelb** [comment]
It seems there is a side effect #53.
